@baseUrl = http://localhost:3000/api/v1

### 1. CREATE USER (POST)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "firstName": "rahan",
  "lastName": "JS",
  "email": "rahan@example.com",
  "phoneNumber": "+919876543219",
  "password": "securePassword123"
}

### 2. LIST ALL (No Pagination)
GET {{baseUrl}}/users

### 3. LIST WITH PAGINATION, SORTING & FILTERING
# Tests sorting by name and filtering by email
GET {{baseUrl}}/users?filterField=firstName&filterValue=rahan

### 4. GET SINGLE USER (404 Test if ID is wrong)
GET {{baseUrl}}/users/1

### 5. UPDATE USER (PATCH)
PATCH {{baseUrl}}/users/1
Content-Type: application/json

{
  "firstName": "Gauresh-Updated"
}

### 6. DELETE USER (204 No Content)
DELETE {{baseUrl}}/users/1

### 7. AUTH TEST (401 Unauthorized)
GET {{baseUrl}}/users/secure-data
auth-key: my-secret-key
role: admin

### 8. 500 INTERNAL SERVER ERROR
GET {{baseUrl}}/users/isr

### 9. 504 GATEWAY TIMEOUT 
GET {{baseUrl}}/users/timeout

### 10. 502 BAD GATEWAY 
GET {{baseUrl}}/users/badgateway

### 11. 422 UNPROCESSABLE ENTITY (Duplicate Email)

POST {{baseUrl}}/users
Content-Type: application/json

{
  "firstName": "Zavian",
  "lastName": "Art",
  "email": "gauresh@example.com",
  "phoneNumber": "+919876543219",
  "password": "securePassword123"
}